export type Lang = "en" | "sw";

export const COPY = {
  en: {
    h1: "Over 1.5 football trebles",
    lead: "Three legs. One slip. You place it.",
    open: "Open trebles",
    signIn: "Sign in",
    create: "Create account",
    signedOut: "Signed out. Your slips stay on the account. Sign in when you want them again.",
    howT: "How a visit works",
    s1t: "See today's list",
    s1p: "Open Casuya Treble and today's football matches arrive with their Over 1.5 prices.",
    s2t: "We pick the legs",
    s2p: "Casuya keeps three legs on one date when their prices multiply to 3.00 or more. If they fall short, the slip is marked Forced and shows the price they do multiply to.",
    s3t: "Place it yourself",
    s3p: "Copy the slip, check the live price with your bookmaker, then stake it by hand.",
    resT: "Placed results",
    resP: "Open to everyone. A leg wins at two goals, and loses only when the match ends short.",
    stake: "Stake: TZS {s} on each match and TZS {s} on each treble.",
    resultsFor: "Results for {date}.",
    g1: "Single matches",
    g2: "Trebles",
    matchesWon: "Matches won",
    matchesLost: "Matches lost",
    waiting: "Waiting",
    single: "Single profit",
    treblesPlaced: "Trebles placed",
    tw: "Won",
    treble: "Treble profit",
    share: "Trebles can share legs. Lost trebles can include the same losing match.",
    once: "The same three matches appear once, even when more than one account placed them.",
    warn: "These results cover the days shown. Past results do not guarantee future ones.",
    auto: "This page refreshes on its own.",
    lu: "Last updated",
    trustT: "What you can count on",
    t1t: "90 days",
    t1p: "Slips stay on your account.",
    t2t: "Labeled practice",
    t2p: "Practice matches leave once real fixtures are loaded.",
    t3t: "Live price",
    t3p: "Check the price with your bookmaker before you stake. Casuya Treble does not place the bet.",
    ctaT: "Today's list is ready",
    ctaP: "Open the trebles, copy the slip and check the live price before you stake.",
    ctaSignedOut: "Your account is still here",
    ctaSignedOutP: "Sign in to open today's list. Your slips stay on the account.",
    visitToday: "Today",
    visitYesterday: "Yesterday",
    visitWeek: "This week",
    visitYear: "This year",
    f1: "18+ only. Bet responsibly.",
    f2: "Casuya Treble does not place the bet and does not guarantee wins. Only stake what you can afford to lose.",
    ex: "Example treble",
    combined: "Combined price",
    exn: "Example prices. Casuya Treble keeps a treble only at 3.00 or more.",
    leg: "Leg",
    o15: "Over 1.5",
    Won: "Won",
    Lost: "Lost",
    Pending: "Waiting",
    practice: "Practice",
    loading: "Loading results…",
    empty: "No placed trebles yet. Mark a slip as placed and the result shows here.",
    error: "Results are unavailable right now.",
    waitingMatches: "Waiting matches",
  },
  sw: {
    h1: "Treble za mpira, Over 1.5",
    lead: "Mechi tatu. Tiketi moja. Unaweka mwenyewe.",
    open: "Fungua treble",
    signIn: "Ingia",
    create: "Fungua akaunti",
    signedOut: "Umetoka. Tiketi zako zinabaki kwenye akaunti. Ingia tena unapozitaka.",
    howT: "Jinsi inavyofanya kazi",
    s1t: "Angalia orodha ya leo",
    s1p: "Fungua Casuya Treble, mechi za mpira za leo zinakuja na bei zake za Over 1.5.",
    s2t: "Tunachagua mechi",
    s2p: "Casuya huchagua mechi tatu za siku moja bei zake zikizidishwa zikifika 3.00 au zaidi. Zisipofika, tiketi inaandikwa Forced na inaonyesha bei inayopatikana.",
    s3t: "Weka mwenyewe",
    s3p: "Nakili tiketi, hakiki bei ya sasa kwa kampuni yako ya kubashiri, kisha weka dau kwa mkono.",
    resT: "Matokeo ya tiketi zilizowekwa",
    resP: "Wazi kwa kila mtu. Mechi inashinda mabao mawili yakishaingia, na inashindwa tu mechi inapoisha na mabao chini ya mawili.",
    stake: "Dau: TZS {s} kwa kila mechi na TZS {s} kwa kila treble.",
    resultsFor: "Matokeo ya {date}.",
    g1: "Mechi moja moja",
    g2: "Treble",
    matchesWon: "Mechi zilizoshinda",
    matchesLost: "Mechi zilizoshindwa",
    waiting: "Zinazosubiri",
    single: "Faida ya mechi moja moja",
    treblesPlaced: "Treble zilizowekwa",
    tw: "Zilizoshinda",
    treble: "Faida ya treble",
    share: "Treble zinaweza kutumia mechi zilezile. Treble zilizoshindwa zinaweza kuwa na mechi moja iliyoshindwa.",
    once: "Mechi tatu zilezile zinaonekana mara moja, hata kama akaunti nyingi ziliweka.",
    warn: "Matokeo haya ni ya siku zinazoonekana. Matokeo ya zamani hayahakikishi yajayo.",
    auto: "Ukurasa huu hujisasisha wenyewe.",
    lu: "Imesasishwa",
    trustT: "Unachoweza kutegemea",
    t1t: "Siku 90",
    t1p: "Tiketi zako hubaki kwenye akaunti yako.",
    t2t: "Mazoezi yamewekewa alama",
    t2p: "Mechi za mazoezi huondoka mechi halisi zikipakiwa.",
    t3t: "Bei ya sasa",
    t3p: "Hakiki bei kwa kampuni yako ya kubashiri kabla ya kuweka dau. Casuya Treble haiweki dau.",
    ctaT: "Orodha ya leo iko tayari",
    ctaP: "Fungua treble, nakili tiketi na hakiki bei ya sasa kabla ya kuweka dau.",
    ctaSignedOut: "Akaunti yako bado iko",
    ctaSignedOutP: "Ingia ili ufungue orodha ya leo. Tiketi zako zinabaki kwenye akaunti.",
    visitToday: "Leo",
    visitYesterday: "Jana",
    visitWeek: "Wiki hii",
    visitYear: "Mwaka huu",
    f1: "Miaka 18+ pekee. Bashiri kwa uwajibikaji.",
    f2: "Casuya Treble haiweki dau na haihakikishi ushindi. Weka dau kiasi unachoweza kukipoteza tu.",
    ex: "Mfano wa treble",
    combined: "Bei ya jumla",
    exn: "Bei za mfano. Casuya Treble huonyesha treble tu ikifika 3.00 au zaidi.",
    leg: "Mechi",
    o15: "Over 1.5",
    Won: "Imeshinda",
    Lost: "Imeshindwa",
    Pending: "Inasubiri",
    practice: "Mazoezi",
    loading: "Inapakia matokeo…",
    empty: "Bado hakuna treble zilizowekwa. Weka alama kuwa umeweka tiketi, matokeo yataonekana hapa.",
    error: "Matokeo hayapatikani kwa sasa.",
    waitingMatches: "Mechi zinazosubiri",
  },
} as const;

const MONTHS: Record<Lang, string[]> = {
  en: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
  sw: ["Jan", "Feb", "Mac", "Apr", "Mei", "Jun", "Jul", "Ago", "Sep", "Okt", "Nov", "Des"],
};

/** Weekday headers for the desk calendar, Monday first. */
export const WEEKDAYS: Record<Lang, string[]> = {
  en: ["Mo", "Tu", "We", "Th", "Fr", "Sa", "Su"],
  sw: ["JTT", "JNN", "JTN", "ALH", "IJM", "JMO", "JPL"],
};

export function formatDay(iso: string, lang: Lang): string {
  const [year, month, day] = iso.split("-").map(Number);
  const name = MONTHS[lang][(month || 1) - 1] ?? "";
  return `${day} ${name} ${year}`;
}

/** "2026-10" → "Oct 2026" (or "Okt 2026" in Kiswahili). */
export function formatMonth(month: string, lang: Lang): string {
  const [year, m] = month.split("-").map(Number);
  const name = MONTHS[lang][(m || 1) - 1] ?? "";
  return `${name} ${year}`;
}

export function formatMoney(value: number): string {
  const text = Math.abs(Math.round(value)).toLocaleString("en-US");
  if (value > 0) return `+${text}`;
  if (value < 0) return `−${text}`;
  return "0";
}

export function formatStake(amount: number): string {
  return Math.round(amount).toLocaleString("en-US");
}

export const CURRENCY = "TZS";

export function fill(template: string, values: Record<string, string | number>): string {
  return Object.entries(values).reduce(
    (text, [key, value]) => text.replaceAll(`{${key}}`, String(value)),
    template,
  );
}

export const SHELL = {
  en: {
    menu: "Menu",
    connected: "Connected",
    offline: "Offline",
    logOut: "Log out",
    admin: "Admin",
    all: "All",
    day: "Day",
    night: "Night",
    t0006: "00:00–06:00",
    t0612: "06:00–12:00",
    t1218: "12:00–18:00",
    t1824: "18:00–24:00",
    allDay: "Full day",
    matchDate: "Match date",
    allDates: "All dates",
    pending: "Pending",
    live: "Live",
    won: "Won",
    lost: "Lost",
    placed: "Placed",
    trebleActions: "Treble actions",
    stepMake: "Make a treble",
    stepSlips: "Your slips",
    stepAccount: "Account",
    choiceGoals: "Goals",
    choiceCorners: "Corners",
    markets: "Markets",
    choiceOne: "One",
    choiceThree: "Top 3",
    generateBest: "Generate best treble",
    generateTop: "Generate top 3",
    oneOnly: "One treble only",
    includeAlt: "Include alternatives",
    refresh: "Refresh",
    more: "More",
    hide: "Hide",
    importBetPawa: "Import BetPawa",
    practiceData: "Practice data",
    importOdds: "Import odds",
    syncScores: "Sync scores",
    noTrebles: "No trebles yet",
    noTreblesBody: "Matches load from BetPawa Tanzania when you open this page. Tap Generate best treble.",
    noTreblesAdmin: "Use More, then Import BetPawa, or the Admin page when you want a fresh list.",
    bestPick: "Best pick",
    combinedLabel: "Combined",
    modelWord: "model",
    generated: "Generated",
    practiceTag: "Practice — not a real match",
    copySlip: "Copy all match names",
    copied: "Match names copied",
    copyHelp: "On BetPawa, paste one name into search, open the match, then choose Over 1.5. Do this for every match, then place one accumulator. Check the price before you stake.",
    copyName: "Copy name",
    copyNameHint: "Copy this name for BetPawa search",
    copiedName: "Name copied. Paste it into BetPawa search",
    openStatus: "This bet is not placed on BetPawa yet",
    placedStatus: "You marked this bet as placed on BetPawa",
    markPlaced: "I have placed this bet on BetPawa",
    undoPlaced: "Undo: I have not placed this bet",
    bestReady: "Best treble ready",
    topReady: "{n} trebles ready",
    forced: "Forced",
    forcedReady: "No three matches multiply to 3.00 or more. This selection multiplies to {odds}. It is marked Forced. Place it only if you decide to use it.",
    forcedNote: "Marked Forced because no treble reaches 3.00. The price above is what these matches multiply to. Place it only if you decide to.",
    noTrebleNone: "No matches are loaded yet. Today's list from BetPawa Tanzania is empty, so there is nothing to build a treble from.",
    noTrebleStarted: "{stored} matches are saved. None are still to kick off, so there is no treble to place.",
    noTreblePrice: "{upcoming} matches are still to kick off. None has an Over 1.5 price, so a treble cannot be built.",
    noTrebleFew: "{priced} matches still to kick off have an Over 1.5 price. A treble needs 3 on the same date.",
    noTrebleSpread: "{priced} matches still to kick off have an Over 1.5 price. The fullest date has only {same}. A treble needs 3 matches on the same date.",
    noTrebleOdds: "The fullest date has {same} matches with an Over 1.5 price. No three of them multiply to 3.00 or more.",
    noTrebleFloor: "No treble today. A leg is used only when Over 1.5 is at least an 85% chance and the price is at least 1.20.",
    noTrebleCorners:
      "No corner treble today. A first-half corner leg is used only when the price is at least 1.20 and the corner count says that price is too short.",
    noTrebleWeather: "No treble today. {n} matches were left off for heavy rain, snow, or extreme wind at kickoff.",
    weatherRain: "heavy rain",
    weatherSnow: "snow",
    weatherWind: "extreme wind",
    noTrebleOnDate: "No treble on {date}.",
    noTrebleAdmin: "Use More, then Import BetPawa, for a fresh list.",
    lastSlip: "Latest slip",
    prevWeek: "Previous week",
    nextWeek: "Next week",
    prevMonth: "Previous month",
    nextMonth: "Next month",
    prevYear: "Previous year",
    nextYear: "Next year",
    noTrebleMonth: "No trebles in {month}.",
    noTrebleMonthPrev: "Use Previous month to see earlier slips.",
    noTrebleMonthNext: "Use Next month to see later slips.",
    copyFailed: "Copy failed. Select the text yourself.",
    serverOffline: "Server offline.",
    loadAccount: "Could not load account",
    loadSlips: "Could not load slips",
    refreshFailed: "Could not refresh BetPawa. Use More, then Import BetPawa.",
    refreshFailedOpen: "Could not refresh BetPawa. Open this page again in a moment.",
    somethingWrong: "Something went wrong",
    betpawaUpdated: "BetPawa Tanzania updated: {n} matches.",
    historyAdded: "League scores added: {n}.",
    practiceRemoved: "Removed {n} old practice matches.",
    importAgain: "Import BetPawa is still there if you want to refresh again.",
    importSaved: "BetPawa Tanzania: {n} matches saved. Generate a new treble, then check the price on betpawa.co.tz.",
    practiceLoaded: "{n} practice fixtures loaded",
    oddsImported: "Imported {n} fixtures",
    slipsUpdated: "Updated {n} slips",
    statusesOk: "Statuses up to date",
    loginTitle: "Log in",
    loginSub: "Open your trebles and BetPawa Tanzania tracking.",
    email: "Email",
    password: "Password",
    signingIn: "Signing in…",
    logIn: "Log in",
    createTitle: "Create account",
    createSub: "Free account for Casuya Treble.",
    passwordHint: "Password (min 8 characters)",
    confirmPassword: "Confirm password",
    creating: "Creating…",
    alreadyHave: "Already have an account?",
    forgot: "Forgot password?",
    forgotTitle: "Forgot password",
    forgotSub: "We will send you a link to reset your password.",
    sending: "Sending…",
    sendReset: "Send reset link",
    backLogin: "Back to log in",
    home: "Homepage",
    resetDev: "Reset link",
    resetTitle: "Reset password",
    resetSub: "Choose a new password for your account.",
    resetToken: "Reset token",
    newPassword: "New password",
    savePassword: "Save password",
    saving: "Saving…",
    passwordsMismatch: "Passwords do not match",
    loginFailed: "Login failed",
    registerFailed: "Registration failed",
    requestFailed: "Request failed",
    resetFailed: "Reset failed",
    users: "Users",
    overview: "Overview",
    tools: "Tools",
    trebleLink: "Treble",
    adminOnly: "Admin only",
    adminDenied: "Signed in as {email}. This login cannot list accounts. Sign in as admin@casuyawin.com.",
    accountsLead: "{n} accounts. Disable a user to stop them signing in.",
    userRole: "User",
    active: "Active",
    disabled: "Disabled",
    slipCount: "{n} slips",
    joined: "joined",
    thisAccount: "This account",
    disable: "Disable",
    enable: "Enable",
    overviewLead: "Counts for the whole desk.",
    matches: "Matches",
    toolsLead: "Import matches, load practice data, and sync scores.",
    couldNotLoadAdmin: "Could not load admin",
    disabledUser: "Disabled {email}",
    enabledUser: "Enabled {email}",
    score: "Score",
    slipsWord: "Slips",
    hoops: "Hoops",
    hoopsTitle: "Basketball filter",
    hoopsSub: "Ten strict gates. One failing gate rejects the tip.",
    hoopsBack: "Back to desk",
    prevDay: "Previous day",
    nextDay: "Next day",
    todayBtn: "Today",
    slateWord: "Slate",
    noGames: "No NBA games on {date}.",
    noGamesHint: "Use Previous day to look at other dates.",
    gatesTitle: "Gate rules",
    policyLine: "Strict boolean AND — one failing gate rejects the tip.",
    marketWord: "Market",
    pOverWord: "P(over)",
    edgeWord: "Edge",
    lineWord: "Line",
    pushWord: "Push",
    overWord: "Over",
    underWord: "Under",
    auditNote: "Model OVER verdicts on finished evaluated games (paper — no bets placed).",
    rejectedWord: "Rejected",
    lastScan: "Last scan",
    scanNever: "Not scanned yet",
    auditTitle: "Measured hit rate",
    hitRateWord: "Hit rate",
    tipsWord: "Tips",
    loadHoops: "Could not load basketball data",
    lockedWord: "Locked at T-{n}m",
    reasonWord: "Reason",
    modelTotalWord: "Model total",
    refreshTips: "Refresh",
    gateCount: "{n} of 10 passed",
    noRunYet: "Not evaluated yet",
    autoOnGameDay: "runs automatically on game day once the market line is posted",
    clvWord: "CLV",
    clvAvgWord: "Avg CLV",
    beatCloseWord: "Beat close",
    roiWord: "ROI",
    shadowTitle: "Shadow record",
    shadowNote: "Experimental rules scored on finished games. Never placed — kept apart from the official record.",
    shadowEmpty: "Fills as finished games carry a recorded decision line.",
    showHistory: "Show history",
    hideHistory: "Hide history",
    historyNote: "Historical replay of finished games — the same rules, before any live record existed.",
  },
  sw: {
    menu: "Menyu",
    connected: "Imeunganishwa",
    offline: "Nje ya mtandao",
    logOut: "Toka",
    admin: "Msimamizi",
    all: "Zote",
    day: "Mchana",
    night: "Usiku",
    t0006: "00:00–06:00 Usiku",
    t0612: "06:00–12:00 Asubuhi",
    t1218: "12:00–18:00 Mchana",
    t1824: "18:00–24:00 Jioni",
    allDay: "Siku nzima",
    matchDate: "Tarehe ya mechi",
    allDates: "Tarehe zote",
    pending: "Inasubiri",
    live: "Moja kwa moja",
    won: "Imeshinda",
    lost: "Imeshindwa",
    placed: "Imewekwa",
    trebleActions: "Vitendo vya treble",
    stepMake: "Tengeneza treble",
    stepSlips: "Tiketi zako",
    stepAccount: "Akaunti",
    choiceGoals: "Mabao",
    choiceCorners: "Kona",
    markets: "Masoko",
    choiceOne: "Moja",
    choiceThree: "3 bora",
    generateBest: "Tengeneza treble bora",
    generateTop: "Tengeneza 3 bora",
    oneOnly: "Treble moja tu",
    includeAlt: "Ongeza chaguo zingine",
    refresh: "Onyesha upya",
    more: "Zaidi",
    hide: "Ficha",
    importBetPawa: "Leta kutoka BetPawa",
    practiceData: "Data ya mazoezi",
    importOdds: "Leta odds",
    syncScores: "Sasisha matokeo",
    noTrebles: "Bado hakuna treble",
    noTreblesBody: "Mechi zinatoka BetPawa Tanzania ukifungua ukurasa huu. Gonga Tengeneza treble bora.",
    noTreblesAdmin: "Tumia Zaidi, kisha Leta kutoka BetPawa, au ukurasa wa msimamizi kwa orodha mpya.",
    bestPick: "Chaguo bora",
    combinedLabel: "Jumla",
    modelWord: "modeli",
    generated: "Imetengenezwa",
    practiceTag: "Mazoezi — si mechi halisi",
    copySlip: "Nakili majina ya mechi zote",
    copied: "Majina ya mechi yamenakiliwa",
    copyHelp: "Kwenye BetPawa, bandika jina moja kwenye utafutaji, fungua mechi, kisha chagua Over 1.5. Fanya hivyo kwa kila mechi, kisha weka dau moja la accumulator. Hakiki bei kabla ya kuweka dau.",
    copyName: "Nakili jina",
    copyNameHint: "Nakili jina hili kwa utafutaji wa BetPawa",
    copiedName: "Jina limenakiliwa. Bandika kwenye utafutaji wa BetPawa",
    openStatus: "Dau hili bado halijawekwa kwenye BetPawa",
    placedStatus: "Umeandika kuwa dau hili limewekwa kwenye BetPawa",
    markPlaced: "Nimeweka dau hili kwenye BetPawa",
    undoPlaced: "Rudisha: bado sijaweka dau hili",
    bestReady: "Treble bora iko tayari",
    topReady: "Treble {n} ziko tayari",
    forced: "Forced",
    forcedReady: "Hakuna mechi tatu zinazozidisha kufikia 3.00 au zaidi. Chaguo hili linazidisha hadi {odds}. Limeandikwa Forced. Liweke tu ukiamua kulitumia.",
    forcedNote: "Imeandikwa Forced kwa sababu hakuna treble inayofika 3.00. Bei iliyo juu ndiyo mechi hizi zinazozidisha. Weka dau tu ukiamua.",
    noTrebleNone: "Bado hakuna mechi zilizopakiwa. Orodha ya leo kutoka BetPawa Tanzania ni tupu, kwa hiyo hakuna treble ya kutengeneza.",
    noTrebleStarted: "Mechi {stored} zimehifadhiwa. Hakuna iliyobaki kuanza, kwa hiyo hakuna treble ya kuweka.",
    noTreblePrice: "Mechi {upcoming} bado hazijaanza. Hakuna yenye bei ya Over 1.5, kwa hiyo treble haiwezi kutengenezwa.",
    noTrebleFew: "Mechi {priced} ambazo hazijaanza zina bei ya Over 1.5. Treble inahitaji mechi 3 za siku moja.",
    noTrebleSpread: "Mechi {priced} ambazo hazijaanza zina bei ya Over 1.5. Siku iliyo na mechi nyingi zaidi ina {same} tu. Treble inahitaji mechi 3 za siku moja.",
    noTrebleOdds: "Siku iliyo na mechi nyingi zaidi ina mechi {same} zenye bei ya Over 1.5. Hakuna tatu zinazozidisha kufikia 3.00 au zaidi.",
    noTrebleFloor: "Hakuna treble leo. Mechi inaingia treble tu ikiwa nafasi ya Over 1.5 ni angalau 85% na bei ni angalau 1.20.",
    noTrebleCorners:
      "Hakuna treble ya kona leo. Mechi ya kona ya kipindi cha kwanza inaingia tu ikiwa bei ni angalau 1.20 na hesabu ya kona inaonyesha bei hiyo ni ndogo.",
    noTrebleWeather: "Hakuna treble leo. Mechi {n} zimeachwa kwa mvua kubwa, theluji, au upepo mkali wakati wa kuanza.",
    weatherRain: "mvua kubwa",
    weatherSnow: "theluji",
    weatherWind: "upepo mkali",
    noTrebleOnDate: "Hakuna treble tarehe {date}.",
    noTrebleAdmin: "Tumia Zaidi, kisha Leta kutoka BetPawa, kwa orodha mpya.",
    lastSlip: "Tiketi ya hivi karibuni",
    prevWeek: "Wiki iliyopita",
    nextWeek: "Wiki ijayo",
    prevMonth: "Mwezi uliopita",
    nextMonth: "Mwezi unaofuata",
    prevYear: "Mwaka uliopita",
    nextYear: "Mwaka ujao",
    noTrebleMonth: "Hakuna treble mwezi {month}.",
    noTrebleMonthPrev: "Tumia Mwezi uliopita kuona tiketi za awali.",
    noTrebleMonthNext: "Tumia Mwezi unaofuata kuona tiketi za baadaye.",
    copyFailed: "Nakili imeshindwa. Chagua maandishi mwenyewe.",
    serverOffline: "Seva haipatikani.",
    loadAccount: "Imeshindwa kupakia akaunti",
    loadSlips: "Imeshindwa kupakia tiketi",
    refreshFailed: "Imeshindwa kusasisha BetPawa. Tumia Zaidi, kisha Leta kutoka BetPawa.",
    refreshFailedOpen: "Imeshindwa kusasisha BetPawa. Fungua ukurasa huu tena baada ya muda mfupi.",
    somethingWrong: "Kuna hitilafu",
    betpawaUpdated: "BetPawa Tanzania imesasishwa: mechi {n}.",
    historyAdded: "Matokeo ya ligi yameongezwa: {n}.",
    practiceRemoved: "Mechi {n} za mazoezi zimeondolewa.",
    importAgain: "Leta kutoka BetPawa bado ipo ukitaka kusasisha tena.",
    importSaved: "BetPawa Tanzania: mechi {n} zimehifadhiwa. Tengeneza treble mpya, kisha hakiki bei kwenye betpawa.co.tz.",
    practiceLoaded: "Mechi {n} za mazoezi zimepakiwa",
    oddsImported: "Mechi {n} zimeletwa",
    slipsUpdated: "Tiketi {n} zimesasishwa",
    statusesOk: "Hali ziko sawa",
    loginTitle: "Ingia",
    loginSub: "Fungua treble zako na ufuatiliaji wa BetPawa Tanzania.",
    email: "Barua pepe",
    password: "Nenosiri",
    signingIn: "Inaingia…",
    logIn: "Ingia",
    createTitle: "Fungua akaunti",
    createSub: "Akaunti ya bure ya Casuya Treble.",
    passwordHint: "Nenosiri (herufi 8 au zaidi)",
    confirmPassword: "Thibitisha nenosiri",
    creating: "Inaundwa…",
    alreadyHave: "Tayari una akaunti?",
    forgot: "Umesahau nenosiri?",
    forgotTitle: "Umesahau nenosiri",
    forgotSub: "Tutakutumia kiungo cha kubadilisha nenosiri.",
    sending: "Inatuma…",
    sendReset: "Tuma kiungo",
    backLogin: "Rudi kuingia",
    home: "Ukurasa mkuu",
    resetDev: "Kiungo cha kubadilisha",
    resetTitle: "Badilisha nenosiri",
    resetSub: "Chagua nenosiri jipya la akaunti yako.",
    resetToken: "Tokeni ya kubadilisha",
    newPassword: "Nenosiri jipya",
    savePassword: "Hifadhi nenosiri",
    saving: "Inahifadhi…",
    passwordsMismatch: "Manenosiri hayafanani",
    loginFailed: "Kuingia kumeshindwa",
    registerFailed: "Kufungua akaunti kumeshindwa",
    requestFailed: "Ombi limeshindwa",
    resetFailed: "Kubadilisha kumeshindwa",
    users: "Watumiaji",
    overview: "Muhtasari",
    tools: "Zana",
    trebleLink: "Treble",
    adminOnly: "Msimamizi pekee",
    adminDenied: "Umeingia kama {email}. Akaunti hii haiwezi kuona orodha. Ingia kama admin@casuyawin.com.",
    accountsLead: "Akaunti {n}. Zima mtumiaji ili asinge.",
    userRole: "Mtumiaji",
    active: "Hai",
    disabled: "Imezimwa",
    slipCount: "Tiketi {n}",
    joined: "alijiunga",
    thisAccount: "Akaunti hii",
    disable: "Zima",
    enable: "Washa",
    overviewLead: "Hesabu za dawati zima.",
    matches: "Mechi",
    toolsLead: "Leta mechi, pakia mazoezi, na sasisha matokeo.",
    couldNotLoadAdmin: "Imeshindwa kupakia msimamizi",
    disabledUser: "{email} amezimwa",
    enabledUser: "{email} amewashwa",
    score: "Matokeo",
    slipsWord: "Tiketi",
    hoops: "Kikapu",
    hoopsTitle: "Kichujio cha mpira wa kikapu",
    hoopsSub: "Milango kumi kali. Milango moja ikishindwa, pendekezo linaondolewa.",
    hoopsBack: "Rudi mezani",
    prevDay: "Siku iliyopita",
    nextDay: "Siku inayofuata",
    todayBtn: "Leo",
    slateWord: "Orodha",
    noGames: "Hakuna mechi za NBA tarehe {date}.",
    noGamesHint: "Tumia Siku iliyopita kuangalia tarehe nyingine.",
    gatesTitle: "Sheria za milango",
    policyLine: "AND kali — milango moja ikishindwa, pendekezo linaondolewa.",
    marketWord: "Soko",
    pOverWord: "P(over)",
    edgeWord: "Faida",
    lineWord: "Bei",
    pushWord: "Sawa",
    overWord: "Over",
    underWord: "Under",
    auditNote: "Uamuzi wa OVER wa modeli kwenye michezo iliyopimwa (karatasi — hakuna dau halisi).",
    rejectedWord: "Imekataliwa",
    lastScan: "Uchunguzi wa mwisho",
    scanNever: "Bado haujachunguzwa",
    auditTitle: "Kiwango halisi cha kushinda",
    hitRateWord: "Kiwango cha kushinda",
    tipsWord: "Pendekezo",
    loadHoops: "Hakuweza kupata data ya kikapu",
    lockedWord: "Imefungwa T-{n}m",
    reasonWord: "Sababu",
    modelTotalWord: "Jumla ya modeli",
    refreshTips: "Sasisha",
    gateCount: "Kati ya 10 zimepita: {n}",
    noRunYet: "Bado haijapimwa",
    autoOnGameDay: "hupimwa yenyewe siku ya mchezo mara mstari wa soko ukiwekwa",
    clvWord: "CLV",
    clvAvgWord: "CLV wastani",
    beatCloseWord: "Kufunga vizuri",
    roiWord: "ROI",
    shadowTitle: "Rekodi ya kivuli",
    shadowNote: "Kanuni za majaribio zilizopimwa kwenye mechi zilizokamilika. Haziwekwi — zinatenganishwa na rekodi rasmi.",
    shadowEmpty: "Inajaa mechi zilizokamilika zikiwa na mstari wa uamuzi uliorekodiwa.",
    showHistory: "Onyesha historia",
    hideHistory: "Ficha historia",
    historyNote: "Mchezo wa kihistoria wa mechi zilizokamilika — kanuni hizo hizo, kabla ya rekodi ya moja kwa moja.",
  },
} as const;
