export type Lang = "en" | "sw";

export const COPY = {
  en: {
    h1: "Over 1.5 football slips",
    lead: "One to three teams. One slip. You place it.",
    open: "Open slips",
    signIn: "Sign in",
    create: "Create account",
    signedOut: "Signed out. Your slips stay on the account. Sign in when you want them again.",
    howT: "How a visit works",
    s1t: "See today's list",
    s1p: "Open Casuya Treble and today's football matches arrive with their Over 1.5 prices.",
    s2t: "We pick the legs",
    s2p: "Casuya builds each slip from one, two, or three teams on the same date, so their prices multiply to between 1.90 and 2.50. No team repeats across a run.",
    s3t: "Place it yourself",
    s3p: "Copy the slip, check the live price with your bookmaker, then stake it by hand.",
    resT: "Placed results",
    resP: "Open to everyone. A leg wins at two goals, and loses only when the match ends short.",
    stake: "Stake: TZS {s} on each match and TZS {s} on each slip.",
    resultsFor: "Results for {date}.",
    g1: "Single matches",
    g2: "Multi-leg slips",
    matchesWon: "Matches won",
    matchesLost: "Matches lost",
    waiting: "Waiting",
    single: "Single profit",
    treblesPlaced: "Slips placed",
    tw: "Won",
    treble: "Slip profit",
    share: "Each team is used in one slip per run, so no two slips repeat the same pick.",
    once: "The same matches appear once, even when more than one account placed them.",
    warn: "These results cover the days shown. Past results do not guarantee future ones.",
    auto: "This page refreshes on its own.",
    lu: "Last updated",
    trustT: "What you can count on",
    t1t: "90 days",
    t1p: "Slips stay on your account.",
    t2t: "Labeled practice",
    t2p: "Practice matches leave once real fixtures are loaded.",
    t3t: "Live price",
    t3p: "Check the price with your bookmaker before you stake. Casuya Treble does not place the bet.",
    ctaT: "Today's list is ready",
    ctaP: "Open the slips, copy the slip and check the live price before you stake.",
    ctaSignedOut: "Your account is still here",
    ctaSignedOutP: "Sign in to open today's list. Your slips stay on the account.",
    visitToday: "Today",
    visitYesterday: "Yesterday",
    visitWeek: "This week",
    visitYear: "This year",
    f1: "18+ only. Bet responsibly.",
    f2: "Casuya Treble does not place the bet and does not guarantee wins. Only stake what you can afford to lose.",
    ex: "Example slip",
    combined: "Combined price",
    exn: "Example prices. Casuya Treble keeps a slip only when its odds land between 1.90 and 2.50.",
    leg: "Leg",
    o15: "Over 1.5",
    Won: "Won",
    Lost: "Lost",
    Pending: "Waiting",
    practice: "Practice",
    loading: "Loading results…",
    empty: "No placed slips yet. Mark a slip as placed and the result shows here.",
    error: "Results are unavailable right now.",
    waitingMatches: "Waiting matches",
  },
  sw: {
    h1: "Slips za mpira, Over 1.5",
    lead: "Timu moja hadi tatu. Tiketi moja. Unaweka mwenyewe.",
    open: "Fungua slips",
    signIn: "Ingia",
    create: "Fungua akaunti",
    signedOut: "Umetoka. Tiketi zako zinabaki kwenye akaunti. Ingia tena unapozitaka.",
    howT: "Jinsi inavyofanya kazi",
    s1t: "Angalia orodha ya leo",
    s1p: "Fungua Casuya Treble, mechi za mpira za leo zinakuja na bei zake za Over 1.5.",
    s2t: "Tunachagua mechi",
    s2p: "Casuya huunda kila tiketi kwa timu moja, mbili, au tatu za siku moja, bei zake zikizidishwa zikifikia kati ya 1.90 na 2.50. Hakuna timu inayorudiwa kwenye mzunguko mmoja.",
    s3t: "Weka mwenyewe",
    s3p: "Nakili tiketi, hakiki bei ya sasa kwa kampuni yako ya kubashiri, kisha weka dau kwa mkono.",
    resT: "Matokeo ya tiketi zilizowekwa",
    resP: "Wazi kwa kila mtu. Mechi inashinda mabao mawili yakishaingia, na inashindwa tu mechi inapoisha na mabao chini ya mawili.",
    stake: "Dau: TZS {s} kwa kila mechi na TZS {s} kwa kila tiketi.",
    resultsFor: "Matokeo ya {date}.",
    g1: "Mechi moja moja",
    g2: "Tiketi za timu nyingi",
    matchesWon: "Mechi zilizoshinda",
    matchesLost: "Mechi zilizoshindwa",
    waiting: "Zinazosubiri",
    single: "Faida ya mechi moja moja",
    treblesPlaced: "Tiketi zilizowekwa",
    tw: "Zilizoshinda",
    treble: "Faida ya tiketi",
    share: "Kila timu hutumika kwenye tiketi moja tu kwa mzunguko, hivyo tiketi mbili hazirudii mechi zilezile.",
    once: "Mechi zilezile zinaonekana mara moja, hata kama akaunti nyingi ziliweka.",
    warn: "Matokeo haya ni ya siku zinazoonekana. Matokeo ya zamani hayahakikishi yajayo.",
    auto: "Ukurasa huu hujisasisha wenyewe.",
    lu: "Imesasishwa",
    trustT: "Unachoweza kutegemea",
    t1t: "Siku 90",
    t1p: "Tiketi zako hubaki kwenye akaunti yako.",
    t2t: "Mazoezi yamewekewa alama",
    t2p: "Mechi za mazoezi huondoka mechi halisi zikipakiwa.",
    t3t: "Bei ya sasa",
    t3p: "Hakiki bei kwa kampuni yako ya kubashiri kabla ya kuweka dau. Casuya Treble haiweki dau.",
    ctaT: "Orodha ya leo iko tayari",
    ctaP: "Fungua tiketi, nakili tiketi na hakiki bei ya sasa kabla ya kuweka dau.",
    ctaSignedOut: "Akaunti yako bado iko",
    ctaSignedOutP: "Ingia ili ufungue orodha ya leo. Tiketi zako zinabaki kwenye akaunti.",
    visitToday: "Leo",
    visitYesterday: "Jana",
    visitWeek: "Wiki hii",
    visitYear: "Mwaka huu",
    f1: "Miaka 18+ pekee. Bashiri kwa uwajibikaji.",
    f2: "Casuya Treble haiweki dau na haihakikishi ushindi. Weka dau kiasi unachoweza kukipoteza tu.",
    ex: "Mfano wa tiketi",
    combined: "Bei ya jumla",
    exn: "Bei za mfano. Casuya Treble huonyesha tiketi tu bei zake zikifikia kati ya 1.90 na 2.50.",
    leg: "Mechi",
    o15: "Over 1.5",
    Won: "Imeshinda",
    Lost: "Imeshindwa",
    Pending: "Inasubiri",
    practice: "Mazoezi",
    loading: "Inapakia matokeo…",
    empty: "Bado hakuna tiketi zilizowekwa. Weka alama kuwa umeweka tiketi, matokeo yataonekana hapa.",
    error: "Matokeo hayapatikani kwa sasa.",
    waitingMatches: "Mechi zinazosubiri",
  },
} as const;

const MONTHS: Record<Lang, string[]> = {
  en: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
  sw: ["Jan", "Feb", "Mac", "Apr", "Mei", "Jun", "Jul", "Ago", "Sep", "Okt", "Nov", "Des"],
};

/** Weekday headers for the desk calendar, Monday first. */
export const WEEKDAYS: Record<Lang, string[]> = {
  en: ["Mo", "Tu", "We", "Th", "Fr", "Sa", "Su"],
  sw: ["JTT", "JNN", "JTN", "ALH", "IJM", "JMO", "JPL"],
};

export function formatDay(iso: string, lang: Lang): string {
  const [year, month, day] = iso.split("-").map(Number);
  const name = MONTHS[lang][(month || 1) - 1] ?? "";
  return `${day} ${name} ${year}`;
}

/** "2026-10" → "Oct 2026" (or "Okt 2026" in Kiswahili). */
export function formatMonth(month: string, lang: Lang): string {
  const [year, m] = month.split("-").map(Number);
  const name = MONTHS[lang][(m || 1) - 1] ?? "";
  return `${name} ${year}`;
}

export function formatMoney(value: number): string {
  const text = Math.abs(Math.round(value)).toLocaleString("en-US");
  if (value > 0) return `+${text}`;
  if (value < 0) return `−${text}`;
  return "0";
}

export function formatStake(amount: number): string {
  return Math.round(amount).toLocaleString("en-US");
}

export const CURRENCY = "TZS";

export function fill(template: string, values: Record<string, string | number>): string {
  return Object.entries(values).reduce(
    (text, [key, value]) => text.replaceAll(`{${key}}`, String(value)),
    template,
  );
}

export const SHELL = {
  en: {
    menu: "Menu",
    connected: "Connected",
    offline: "Offline",
    logOut: "Log out",
    admin: "Admin",
    all: "All",
    day: "Day",
    night: "Night",
    t0006: "00:00–06:00",
    t0612: "06:00–12:00",
    t1218: "12:00–18:00",
    t1824: "18:00–24:00",
    allDay: "Full day",
    matchDate: "Match date",
    allDates: "All dates",
    pending: "Pending",
    live: "Live",
    won: "Won",
    lost: "Lost",
    placed: "Placed",
    trebleActions: "Slip actions",
    stepMake: "Make a slip",
    stepSlips: "Your slips",
    stepAccount: "Account",
    choiceGoals: "Goals",
    choiceCorners: "Corners",
    markets: "Markets",
    choiceOne: "One",
    choiceThree: "Top 3",
    generateBest: "Generate best slip",
    generateTop: "Generate top 3",
    replacePendingTitle: "Replace your pending slips?",
    replacePendingBody:
      "Generating now deletes the pending slips you have not placed in these markets ({n}), then builds new ones. This cannot be undone.",
    replacePendingConfirm: "Delete and generate",
    replacePendingCancel: "Keep my slips",
    cornerCalibration: "Corner results",
    cornerCalLine: "Line",
    cornerCalWon: "Won",
    cornerCalSettled: "Settled",
    cornerCalHit: "Hit",
    cornerCalModel: "Model",
    cornerCalOdds: "Odds",
    cornerCalNote: "Hit is what settled bets actually did; Model is what the picker claimed. A line shown in red has underperformed its claim by more than 15 points.",
    oneOnly: "One slip only",
    includeAlt: "Include alternatives",
    refresh: "Refresh",
    more: "More",
    hide: "Hide",
    importBetPawa: "Import BetPawa",
    practiceData: "Practice data",
    importOdds: "Import odds",
    syncScores: "Sync scores",
    noTrebles: "No slips yet",
    noTreblesBody: "Matches load from BetPawa Tanzania when you open this page. Tap Generate best slip.",
    noTreblesAdmin: "Use More, then Import BetPawa, or the Admin page when you want a fresh list.",
    bestPick: "Best pick",
    combinedLabel: "Combined",
    modelWord: "model",
    generated: "Generated",
    practiceTag: "Practice — not a real match",
    copySlip: "Copy all match names",
    copied: "Match names copied",
    copyHelp: "On BetPawa, paste one name into search, open the match, then choose Over 1.5. Do this for every match, then place one accumulator. Check the price before you stake.",
    copyName: "Copy name",
    copyNameHint: "Copy this name for BetPawa search",
    copiedName: "Name copied. Paste it into BetPawa search",
    openStatus: "This bet is not placed on BetPawa yet",
    placedStatus: "You marked this bet as placed on BetPawa",
    markPlaced: "I have placed this bet on BetPawa",
    undoPlaced: "Undo: I have not placed this bet",
    bestReady: "Best slip ready",
    topReady: "{n} slips ready",
    forced: "Forced",
    forcedReady: "No combination lands between 1.90 and 2.50. This selection multiplies to {odds}. Place it only if you decide to use it.",
    forcedNote: "Marked Forced because no combination lands between 1.90 and 2.50. The price above is what these matches multiply to. Place it only if you decide to.",
    noTrebleNone: "No matches are loaded yet. Today's list from BetPawa Tanzania is empty, so there is nothing to build a slip from.",
    noTrebleStarted: "{stored} matches are saved. None are still to kick off, so there is no slip to place.",
    noTreblePrice: "{upcoming} matches are still to kick off. None has an Over 1.5 price, so a slip cannot be built.",
    noTrebleFew: "{priced} matches still to kick off have an Over 1.5 price. A slip needs at least one.",
    noTrebleSpread: "{priced} matches still to kick off have an Over 1.5 price. The fullest date has only {same}. A slip needs its matches on the same date.",
    noTrebleOdds: "The fullest date has {same} matches with an Over 1.5 price. No one, two, or three of them multiply into 1.90–2.50.",
    noTrebleFloor: "No slip today. A leg is used only when Over 1.5 is at least an 80% chance and the price is at least 1.20.",
    noTrebleNoModel:
      "None of the {upcoming} matches still to kick off has a model estimate, so none can be a leg. Only leagues with enough finished matches are rated; the rest are skipped rather than guessed.",
    noTrebleModeled:
      "Only {modeled} of the {upcoming} matches still to kick off have a model estimate. The rest are skipped rather than guessed.",
    noTrebleCorners:
      "No corner slip today. A first-half corner leg is used only when the price is at least 1.20 and the corner count says that price is too short.",
    noTrebleWeather: "No slip today. {n} matches were left off for heavy rain, snow, or extreme wind at kickoff.",
    weatherRain: "heavy rain",
    weatherSnow: "snow",
    weatherWind: "extreme wind",
    noTrebleOnDate: "No slip on {date}.",
    noTrebleAdmin: "Use More, then Import BetPawa, for a fresh list.",
    lastSlip: "Latest slip",
    prevWeek: "Previous week",
    nextWeek: "Next week",
    prevMonth: "Previous month",
    nextMonth: "Next month",
    prevYear: "Previous year",
    nextYear: "Next year",
    noTrebleMonth: "No slips in {month}.",
    noTrebleMonthPrev: "Use Previous month to see earlier slips.",
    noTrebleMonthNext: "Use Next month to see later slips.",
    copyFailed: "Copy failed. Select the text yourself.",
    serverOffline: "Server offline.",
    loadAccount: "Could not load account",
    loadSlips: "Could not load slips",
    refreshFailed: "Could not refresh BetPawa. Use More, then Import BetPawa.",
    refreshFailedOpen: "Could not refresh BetPawa. Open this page again in a moment.",
    somethingWrong: "Something went wrong",
    betpawaUpdated: "BetPawa Tanzania updated: {n} matches.",
    historyAdded: "League scores added: {n}.",
    practiceRemoved: "Removed {n} old practice matches.",
    importAgain: "Import BetPawa is still there if you want to refresh again.",
    importSaved: "BetPawa Tanzania: {n} matches saved. Generate new picks, then check the price on betpawa.co.tz.",
    practiceLoaded: "{n} practice fixtures loaded",
    oddsImported: "Imported {n} fixtures",
    slipsUpdated: "Updated {n} slips",
    statusesOk: "Statuses up to date",
    loginTitle: "Log in",
    loginSub: "Open your slips and BetPawa Tanzania tracking.",
    email: "Email",
    password: "Password",
    signingIn: "Signing in…",
    logIn: "Log in",
    createTitle: "Create account",
    createSub: "Free account for Casuya Treble.",
    passwordHint: "Password (min 8 characters)",
    confirmPassword: "Confirm password",
    creating: "Creating…",
    alreadyHave: "Already have an account?",
    forgot: "Forgot password?",
    forgotTitle: "Forgot password",
    forgotSub: "We will send you a link to reset your password.",
    sending: "Sending…",
    sendReset: "Send reset link",
    backLogin: "Back to log in",
    home: "Homepage",
    resetDev: "Reset link",
    resetTitle: "Reset password",
    resetSub: "Choose a new password for your account.",
    resetToken: "Reset token",
    newPassword: "New password",
    savePassword: "Save password",
    saving: "Saving…",
    passwordsMismatch: "Passwords do not match",
    loginFailed: "Login failed",
    registerFailed: "Registration failed",
    requestFailed: "Request failed",
    resetFailed: "Reset failed",
    users: "Users",
    overview: "Overview",
    tools: "Tools",
    trebleLink: "Treble",
    adminOnly: "Admin only",
    adminDenied: "Signed in as {email}. This login cannot list accounts. Sign in as admin@casuyawin.com.",
    accountsLead: "{n} accounts. Disable a user to stop them signing in.",
    userRole: "User",
    active: "Active",
    disabled: "Disabled",
    slipCount: "{n} slips",
    joined: "joined",
    thisAccount: "This account",
    disable: "Disable",
    enable: "Enable",
    overviewLead: "Counts for the whole desk.",
    matches: "Matches",
    toolsLead: "Import matches, load practice data, and sync scores.",
    couldNotLoadAdmin: "Could not load admin",
    disabledUser: "Disabled {email}",
    enabledUser: "Enabled {email}",
    score: "Score",
    slipsWord: "Slips",
    hoops: "Hoops",
    hoopsTitle: "Basketball filter",
    hoopsSub: "Ten strict gates. One failing gate rejects the tip.",
    hoopsBack: "Back to desk",
    prevDay: "Previous day",
    nextDay: "Next day",
    todayBtn: "Today",
    slateWord: "Slate",
    noGames: "No NBA games on {date}.",
    noGamesHint: "Use Previous day to look at other dates.",
    gatesTitle: "Gate rules",
    policyLine: "Strict boolean AND — one failing gate rejects the tip.",
    marketWord: "Market",
    pOverWord: "P(over)",
    edgeWord: "Edge",
    lineWord: "Line",
    pushWord: "Push",
    overWord: "Over",
    underWord: "Under",
    auditNote: "Model OVER verdicts on finished evaluated games (paper — no bets placed).",
    rejectedWord: "Rejected",
    lastScan: "Last scan",
    scanNever: "Not scanned yet",
    auditTitle: "Measured hit rate",
    hitRateWord: "Hit rate",
    tipsWord: "Tips",
    loadHoops: "Could not load basketball data",
    lockedWord: "Locked at T-{n}m",
    reasonWord: "Reason",
    modelTotalWord: "Model total",
    refreshTips: "Refresh",
    gateCount: "{n} of 10 passed",
    noRunYet: "Not evaluated yet",
    autoOnGameDay: "runs automatically on game day once the market line is posted",
    clvWord: "CLV",
    clvAvgWord: "Avg CLV",
    beatCloseWord: "Beat close",
    roiWord: "ROI",
    shadowTitle: "Shadow record",
    shadowNote: "Experimental rules scored on finished games. Never placed — kept apart from the official record.",
    shadowEmpty: "Fills as finished games carry a recorded decision line.",
    showHistory: "Show history",
    hideHistory: "Hide history",
    historyNote: "Historical replay of finished games — the same rules, before any live record existed.",
    blockersTitle: "Why nothing passed",
    blockersNote:
      "Bar length is the share of evaluated games each gate stopped. The longest bar is the real reason this date produced no tip.",
    blockersCount: "{n} rejected",
    clvWait: "CLV builds up only once a picked game finishes — no finished picks yet.",
    auditDecided: "{n} games decided.",
    oddsRangeNote: "Combined odds must land between 1.90 and 2.50.",
  },
  sw: {
    menu: "Menyu",
    connected: "Imeunganishwa",
    offline: "Nje ya mtandao",
    logOut: "Toka",
    admin: "Msimamizi",
    all: "Zote",
    day: "Mchana",
    night: "Usiku",
    t0006: "00:00–06:00 Usiku",
    t0612: "06:00–12:00 Asubuhi",
    t1218: "12:00–18:00 Mchana",
    t1824: "18:00–24:00 Jioni",
    allDay: "Siku nzima",
    matchDate: "Tarehe ya mechi",
    allDates: "Tarehe zote",
    pending: "Inasubiri",
    live: "Moja kwa moja",
    won: "Imeshinda",
    lost: "Imeshindwa",
    placed: "Imewekwa",
    trebleActions: "Vitendo vya tiketi",
    stepMake: "Tengeneza tiketi",
    stepSlips: "Tiketi zako",
    stepAccount: "Akaunti",
    choiceGoals: "Mabao",
    choiceCorners: "Kona",
    markets: "Masoko",
    choiceOne: "Moja",
    choiceThree: "3 bora",
    generateBest: "Tengeneza tiketi bora",
    generateTop: "Tengeneza 3 bora",
    replacePendingTitle: "Badilisha tiketi zako zinazosubiri?",
    replacePendingBody:
      "Kutengeneza sasa hufuta tiketi zinazosubiri ambazo haujaweka kwenye masoko haya ({n}), kisha hutengeneza mpya. Hili haliwezi kurudishwa.",
    replacePendingConfirm: "Futa na tengeneza",
    replacePendingCancel: "Acha tiketi zangu",
    cornerCalibration: "Matokeo ya kona",
    cornerCalLine: "Laini",
    cornerCalWon: "Zilizoshinda",
    cornerCalSettled: "Zilizomalizika",
    cornerCalHit: "Kiwango",
    cornerCalModel: "Mfano",
    cornerCalOdds: "Odds",
    cornerCalNote: "Kiwango ni kile dau zilizomalizika zilifanya; Mfano ndicho kile mchumaji alidai. Laini yenye rangi nyekundu imefanya vibaya kuliko madai kwa zaidi ya asilimia 15.",
    oneOnly: "Tiketi moja tu",
    includeAlt: "Ongeza chaguo zingine",
    refresh: "Onyesha upya",
    more: "Zaidi",
    hide: "Ficha",
    importBetPawa: "Leta kutoka BetPawa",
    practiceData: "Data ya mazoezi",
    importOdds: "Leta odds",
    syncScores: "Sasisha matokeo",
    noTrebles: "Bado hakuna tiketi",
    noTreblesBody: "Mechi zinatoka BetPawa Tanzania ukifungua ukurasa huu. Gonga Tengeneza tiketi bora.",
    noTreblesAdmin: "Tumia Zaidi, kisha Leta kutoka BetPawa, au ukurasa wa msimamizi kwa orodha mpya.",
    bestPick: "Chaguo bora",
    combinedLabel: "Jumla",
    modelWord: "modeli",
    generated: "Imetengenezwa",
    practiceTag: "Mazoezi — si mechi halisi",
    copySlip: "Nakili majina ya mechi zote",
    copied: "Majina ya mechi yamenakiliwa",
    copyHelp: "Kwenye BetPawa, bandika jina moja kwenye utafutaji, fungua mechi, kisha chagua Over 1.5. Fanya hivyo kwa kila mechi, kisha weka dau moja la accumulator. Hakiki bei kabla ya kuweka dau.",
    copyName: "Nakili jina",
    copyNameHint: "Nakili jina hili kwa utafutaji wa BetPawa",
    copiedName: "Jina limenakiliwa. Bandika kwenye utafutaji wa BetPawa",
    openStatus: "Dau hili bado halijawekwa kwenye BetPawa",
    placedStatus: "Umeandika kuwa dau hili limewekwa kwenye BetPawa",
    markPlaced: "Nimeweka dau hili kwenye BetPawa",
    undoPlaced: "Rudisha: bado sijaweka dau hili",
    bestReady: "Tiketi bora iko tayari",
    topReady: "Tiketi {n} ziko tayari",
    forced: "Forced",
    forcedReady: "Hakuna muunganiko unaofikia kati ya 1.90 na 2.50. Chaguo hili linazidisha hadi {odds}. Liweke tu ukiamua kulitumia.",
    forcedNote: "Imeandikwa Forced kwa sababu hakuna muunganiko unaofikia 1.90–2.50. Bei iliyo juu ndiyo mechi hizi zinazozidisha. Weka dau tu ukiamua.",
    noTrebleNone: "Bado hakuna mechi zilizopakiwa. Orodha ya leo kutoka BetPawa Tanzania ni tupu, kwa hiyo hakuna tiketi ya kutengeneza.",
    noTrebleStarted: "Mechi {stored} zimehifadhiwa. Hakuna iliyobaki kuanza, kwa hiyo hakuna tiketi ya kuweka.",
    noTreblePrice: "Mechi {upcoming} bado hazijaanza. Hakuna yenye bei ya Over 1.5, kwa hiyo tiketi haiwezi kutengenezwa.",
    noTrebleFew: "Mechi {priced} ambazo hazijaanza zina bei ya Over 1.5. Tiketi inahitaji mechi moja angalau.",
    noTrebleSpread: "Mechi {priced} ambazo hazijaanza zina bei ya Over 1.5. Siku iliyo na mechi nyingi zaidi ina {same} tu. Tiketi inahitaji mechi zake ziwe siku moja.",
    noTrebleOdds: "Siku iliyo na mechi nyingi zaidi ina mechi {same} zenye bei ya Over 1.5. Hakuna moja, mbili, au tatu zinazozidisha kufikia 1.90–2.50.",
    noTrebleFloor: "Hakuna tiketi leo. Mechi inaingia tiketi tu ikiwa nafasi ya Over 1.5 ni angalau 80% na bei ni angalau 1.20.",
    noTrebleNoModel:
      "Kati ya mechi {upcoming} bado hazijaanza, hakuna inayo na makadirio ya modeli, kwa hiyo hakuna inayoweza kuwa mguu. Tunapanga tu ligi zenye mechi za kutosha zilizomalika; zingine zinaachwa badala ya kuduwaa.",
    noTrebleModeled:
      "Kati ya mechi {upcoming} bado hazijaanza, ni {modeled} tu zenye makadirio ya modeli. Zingine zinaachwa badala ya kuduwaa.",
    noTrebleCorners:
      "Hakuna tiketi ya kona leo. Mechi ya kona ya kipindi cha kwanza inaingia tu ikiwa bei ni angalau 1.20 na hesabu ya kona inaonyesha bei hiyo ni ndogo.",
    noTrebleWeather: "Hakuna tiketi leo. Mechi {n} zimeachwa kwa mvua kubwa, theluji, au upepo mkali wakati wa kuanza.",
    weatherRain: "mvua kubwa",
    weatherSnow: "theluji",
    weatherWind: "upepo mkali",
    noTrebleOnDate: "Hakuna tiketi tarehe {date}.",
    noTrebleAdmin: "Tumia Zaidi, kisha Leta kutoka BetPawa, kwa orodha mpya.",
    lastSlip: "Tiketi ya hivi karibuni",
    prevWeek: "Wiki iliyopita",
    nextWeek: "Wiki ijayo",
    prevMonth: "Mwezi uliopita",
    nextMonth: "Mwezi unaofuata",
    prevYear: "Mwaka uliopita",
    nextYear: "Mwaka ujao",
    noTrebleMonth: "Hakuna tiketi mwezi {month}.",
    noTrebleMonthPrev: "Tumia Mwezi uliopita kuona tiketi za awali.",
    noTrebleMonthNext: "Tumia Mwezi unaofuata kuona tiketi za baadaye.",
    copyFailed: "Nakili imeshindwa. Chagua maandishi mwenyewe.",
    serverOffline: "Seva haipatikani.",
    loadAccount: "Imeshindwa kupakia akaunti",
    loadSlips: "Imeshindwa kupakia tiketi",
    refreshFailed: "Imeshindwa kusasisha BetPawa. Tumia Zaidi, kisha Leta kutoka BetPawa.",
    refreshFailedOpen: "Imeshindwa kusasisha BetPawa. Fungua ukurasa huu tena baada ya muda mfupi.",
    somethingWrong: "Kuna hitilafu",
    betpawaUpdated: "BetPawa Tanzania imesasishwa: mechi {n}.",
    historyAdded: "Matokeo ya ligi yameongezwa: {n}.",
    practiceRemoved: "Mechi {n} za mazoezi zimeondolewa.",
    importAgain: "Leta kutoka BetPawa bado ipo ukitaka kusasisha tena.",
    importSaved: "BetPawa Tanzania: mechi {n} zimehifadhiwa. Tengeneza chaguo mpya, kisha hakiki bei kwenye betpawa.co.tz.",
    practiceLoaded: "Mechi {n} za mazoezi zimepakiwa",
    oddsImported: "Mechi {n} zimeletwa",
    slipsUpdated: "Tiketi {n} zimesasishwa",
    statusesOk: "Hali ziko sawa",
    loginTitle: "Ingia",
    loginSub: "Fungua tiketi zako na ufuatiliaji wa BetPawa Tanzania.",
    email: "Barua pepe",
    password: "Nenosiri",
    signingIn: "Inaingia…",
    logIn: "Ingia",
    createTitle: "Fungua akaunti",
    createSub: "Akaunti ya bure ya Casuya Treble.",
    passwordHint: "Nenosiri (herufi 8 au zaidi)",
    confirmPassword: "Thibitisha nenosiri",
    creating: "Inaundwa…",
    alreadyHave: "Tayari una akaunti?",
    forgot: "Umesahau nenosiri?",
    forgotTitle: "Umesahau nenosiri",
    forgotSub: "Tutakutumia kiungo cha kubadilisha nenosiri.",
    sending: "Inatuma…",
    sendReset: "Tuma kiungo",
    backLogin: "Rudi kuingia",
    home: "Ukurasa mkuu",
    resetDev: "Kiungo cha kubadilisha",
    resetTitle: "Badilisha nenosiri",
    resetSub: "Chagua nenosiri jipya la akaunti yako.",
    resetToken: "Tokeni ya kubadilisha",
    newPassword: "Nenosiri jipya",
    savePassword: "Hifadhi nenosiri",
    saving: "Inahifadhi…",
    passwordsMismatch: "Manenosiri hayafanani",
    loginFailed: "Kuingia kumeshindwa",
    registerFailed: "Kufungua akaunti kumeshindwa",
    requestFailed: "Ombi limeshindwa",
    resetFailed: "Kubadilisha kumeshindwa",
    users: "Watumiaji",
    overview: "Muhtasari",
    tools: "Zana",
    trebleLink: "Treble",
    adminOnly: "Msimamizi pekee",
    adminDenied: "Umeingia kama {email}. Akaunti hii haiwezi kuona orodha. Ingia kama admin@casuyawin.com.",
    accountsLead: "Akaunti {n}. Zima mtumiaji ili asinge.",
    userRole: "Mtumiaji",
    active: "Hai",
    disabled: "Imezimwa",
    slipCount: "Tiketi {n}",
    joined: "alijiunga",
    thisAccount: "Akaunti hii",
    disable: "Zima",
    enable: "Washa",
    overviewLead: "Hesabu za dawati zima.",
    matches: "Mechi",
    toolsLead: "Leta mechi, pakia mazoezi, na sasisha matokeo.",
    couldNotLoadAdmin: "Imeshindwa kupakia msimamizi",
    disabledUser: "{email} amezimwa",
    enabledUser: "{email} amewashwa",
    score: "Matokeo",
    slipsWord: "Tiketi",
    hoops: "Kikapu",
    hoopsTitle: "Kichujio cha mpira wa kikapu",
    hoopsSub: "Milango kumi kali. Milango moja ikishindwa, pendekezo linaondolewa.",
    hoopsBack: "Rudi mezani",
    prevDay: "Siku iliyopita",
    nextDay: "Siku inayofuata",
    todayBtn: "Leo",
    slateWord: "Orodha",
    noGames: "Hakuna mechi za NBA tarehe {date}.",
    noGamesHint: "Tumia Siku iliyopita kuangalia tarehe nyingine.",
    gatesTitle: "Sheria za milango",
    policyLine: "AND kali — milango moja ikishindwa, pendekezo linaondolewa.",
    marketWord: "Soko",
    pOverWord: "P(over)",
    edgeWord: "Faida",
    lineWord: "Bei",
    pushWord: "Sawa",
    overWord: "Over",
    underWord: "Under",
    auditNote: "Uamuzi wa OVER wa modeli kwenye michezo iliyopimwa (karatasi — hakuna dau halisi).",
    rejectedWord: "Imekataliwa",
    lastScan: "Uchunguzi wa mwisho",
    scanNever: "Bado haujachunguzwa",
    auditTitle: "Kiwango halisi cha kushinda",
    hitRateWord: "Kiwango cha kushinda",
    tipsWord: "Pendekezo",
    loadHoops: "Hakuweza kupata data ya kikapu",
    lockedWord: "Imefungwa T-{n}m",
    reasonWord: "Sababu",
    modelTotalWord: "Jumla ya modeli",
    refreshTips: "Sasisha",
    gateCount: "Kati ya 10 zimepita: {n}",
    noRunYet: "Bado haijapimwa",
    autoOnGameDay: "hupimwa yenyewe siku ya mchezo mara mstari wa soko ukiwekwa",
    clvWord: "CLV",
    clvAvgWord: "CLV wastani",
    beatCloseWord: "Kufunga vizuri",
    roiWord: "ROI",
    shadowTitle: "Rekodi ya kivuli",
    shadowNote: "Kanuni za majaribio zilizopimwa kwenye mechi zilizokamilika. Haziwekwi — zinatenganishwa na rekodi rasmi.",
    shadowEmpty: "Inajaa mechi zilizokamilika zikiwa na mstari wa uamuzi uliorekodiwa.",
    showHistory: "Onyesha historia",
    hideHistory: "Ficha historia",
    historyNote: "Mchezo wa kihistoria wa mechi zilizokamilika — kanuni hizo hizo, kabla ya rekodi ya moja kwa moja.",
    blockersTitle: "Kwa nini hakuna kilichopita",
    blockersNote:
      "Urefu wa muda ni sehemu ya mechi zilizopimwa kila lango lilizozuia. Mrefu zaidi ndilo sababu halisi tarehe hii haikutoa pendekezo.",
    blockersCount: "{n} zimekataliwa",
    clvWait: "CLV huanza mechi moja ya pendekezo ikikamilika — bado hakuna iliyokamilika.",
    auditDecided: "mechi {n} zimeamuliwa.",
    oddsRangeNote: "Bei ya pamoja lazima iwe kati ya 1.90 na 2.50.",
  },
} as const;
